# Generated by Django 5.1.2 on 2024-11-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FchatWebsite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("DEV", "Development"),
                            ("STG", "Staging"),
                            ("UAT", "UAT"),
                            ("PRO", "Production"),
                        ],
                        max_length=3,
                    ),
                ),
                ("scripts", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
